tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "tertiary-container": "#aa5a00",
                "outline-variant": "#c0c7d2",
                "primary": "#005a92",
                "background": "#fbf9f8",
                "surface-container": "#f0eded",
                "on-secondary-fixed-variant": "#3a485c",
                "on-secondary-container": "#57657b",
                "on-primary-container": "#ecf3ff",
                "primary-container": "#0073b9",
                "surface-bright": "#fbf9f8",
                "surface-container-highest": "#e4e2e1",
                "on-secondary": "#ffffff",
                "on-tertiary": "#ffffff",
                "tertiary-fixed": "#ffdcc4",
                "on-tertiary-fixed": "#2f1500",
                "on-primary": "#ffffff",
                "error": "#ba1a1a",
                "primary-fixed": "#d0e4ff",
                "inverse-surface": "#303030",
                "surface-dim": "#dcd9d9",
                "on-primary-fixed": "#001d34",
                "on-surface": "#1b1c1c",
                "on-error": "#ffffff",
                "tertiary": "#864600",
                "primary-fixed-dim": "#9acbff",
                "on-tertiary-container": "#fff1e9",
                "on-background": "#1b1c1c",
                "on-secondary-fixed": "#0d1c2f",
                "secondary": "#515f74",
                "inverse-primary": "#9acbff",
                "surface-container-high": "#eae8e7",
                "on-primary-fixed-variant": "#004a79",
                "tertiary-fixed-dim": "#ffb77f",
                "outline": "#707882",
                "on-surface-variant": "#404751",
                "on-tertiary-fixed-variant": "#6f3900",
                "inverse-on-surface": "#f3f0f0",
                "secondary-fixed-dim": "#b9c7e0",
                "surface-variant": "#e4e2e1",
                "surface": "#fbf9f8",
                "secondary-fixed": "#d5e3fd",
                "secondary-container": "#d5e3fd",
                "surface-container-low": "#f6f3f2",
                "surface-container-lowest": "#ffffff",
                "error-container": "#ffdad6",
                "surface-tint": "#00629f",
                "on-error-container": "#93000a"
            },
            fontFamily: {
                "headline": ["Plus Jakarta Sans", "Noto Sans KR"],
                "body": ["Inter", "Noto Sans KR"],
                "label": ["Inter", "Noto Sans KR"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
}
